### ISSUE TITLE
error when opening file `./results/olc/pre-flye-input-contigs.fa`

### ISSUE THREAD

**Issue by nick-youngblut** [abishara/athena_meta#15]
I got the following error when running athena-meta v1.1: 

```
2018-11-01 22:02:32 - ========== Exception ==========
2018-11-01 22:02:32 - Traceback (most recent call last):
2018-11-01 22:02:32 -   File "build/bdist.linux-x86_64/egg/athena/pipeline.py", line 50, in _run_chunk
2018-11-01 22:02:32 -     chunk.run()
2018-11-01 22:02:32 -   File "build/bdist.linux-x86_64/egg/athena/stages/assemble_olc.py", line 96, in run
2018-11-01 22:02:32 -     premergedfiltfa_path,
2018-11-01 22:02:32 -   File "build/bdist.linux-x86_64/egg/athena/stages/assemble_olc.py", line 160, in filter_inputs
2018-11-01 22:02:32 -     ctg_size_map = util.get_fasta_sizes(mergedfa_path)
2018-11-01 22:02:32 -   File "build/bdist.linux-x86_64/egg/athena/mlib/util.py", line 151, in get_fasta_sizes
2018-11-01 22:02:32 -     fasta = pysam.FastaFile(fa_path)
2018-11-01 22:02:32 -   File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
2018-11-01 22:02:32 -   File "pysam/libcfaidx.pyx", line 183, in pysam.libcfaidx.FastaFile._open
2018-11-01 22:02:32 - IOError: error when opening file `./results/olc/pre-flye-input-contigs.fa`
2018-11-01 22:02:32 -
2018-11-01 22:02:32 - error when opening file `./results/olc/pre-flye-input-contigs.fa`
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/athena/bin/athena-meta", line 11, in <module>
    load_entry_point('athena==1.1', 'console_scripts', 'athena-meta')()
  File "build/bdist.linux-x86_64/egg/main.py", line 104, in main
  File "build/bdist.linux-x86_64/egg/main.py", line 36, in run
  File "build/bdist.linux-x86_64/egg/athena/pipeline.py", line 33, in run_stage
  File "build/bdist.linux-x86_64/egg/athena/cluster.py", line 43, in map
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/athena/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IOError: error when opening file `./results/olc/pre-flye-input-contigs.fa`
```

`./results/olc/pre-flye-input-contigs.fa` is an empty file, so it appears that athena_meta dies if this occurs, and the traceback doesn't show that the problem is an empty file.

**Comment by Zhong17** [comment]
I have the same error information with u , and i wonder is there any solution here? @nick-youngblut

**Comment by nick-youngblut** [comment]
Hi @Zhong17, I think that you don't have enough input sequence data.

**Comment by Zhong17** [comment]
Hi @nick-youngblut , Thanks for replying, actually, the barcoded.fastq were generated by long ranger basic, the raw date were 100G in total, but only have 4M after running long ranger basic, with no N in extracted barcode in BC tag. I still do not know the reason.

**Comment by abishara** [comment]
Hi @Zhong17,

I would contact the software support at 10X genomics to understand why so few of your reads have attached barcodes using their longranger basic software on your dataset.   There isn't much I can help with there.   @nick-youngblut is correct in that there is not enough input sequence for athena to assemble as a result.  More interpretable error messages will be added in an upcoming release.

Thanks,
alex
