### ISSUE TITLE
assembly failed to produce contig.fa

### ISSUE THREAD

**Issue by nick-youngblut** [abishara/athena_meta#16]
It appears that athena_meta v1.1 will die if any of the subassemblies fail to generate contigs:

```
$ athena-meta config.json
============================== bin_reads ==============================
--> 0 chunks need to be run. Skipping...

============================== index_reads ==============================
--> 0 chunks need to be run. Skipping...

============================== assemble_bins ==============================
671 chunks to run. Starting...
2018-11-03 10:10:09 - --starting logging AssembleMetaBinnedStep.bin.3 --
2018-11-03 10:10:09 - performing local assembly for 1 seeds
2018-11-03 10:10:09 - targeting 100x short-read subassembly coverage
2018-11-03 10:10:09 - using barcodes mapped within 10000bp from seed end-points for seed subassembly
2018-11-03 10:10:09 - assembling barcoded reads for seed NODE_331_length_7434_cov_24.498577
2018-11-03 10:10:09 - determing local assemblies
2018-11-03 10:10:09 - 4 initial link candidates to check
2018-11-03 10:10:09 -   - 2 pass reciprocal filtering
2018-11-03 10:10:09 - root-ctg:NODE_331_length_7434_cov_24.498577;numreads:777;checks:4;trunc-checks:False;asms:2;trunc-asms:False
2018-11-03 10:10:09 -   - found 3 candidates
2018-11-03 10:10:09 - performing local assemblies
2018-11-03 10:10:09 -   - skipping filtered contig NODE_66_length_45138_cov_17.962691
2018-11-03 10:10:09 - assembling with neighbor NODE_13841_length_362_cov_30.302932
2018-11-03 10:10:09 -   - 31 orig barcodes
2018-11-03 10:10:09 -   - 31 downsampled barcodes
2018-11-03 10:10:09 -   - 13.381294964x estimated local coverage
2018-11-03 10:10:09 -   - 2 min_support required
:::: 127
2018-11-03 10:10:16 - assembly failed to produce contig.fa
2018-11-03 10:10:16 - ========== Exception ==========
2018-11-03 10:10:16 - Traceback (most recent call last):
2018-11-03 10:10:16 -   File "build/bdist.linux-x86_64/egg/athena/pipeline.py", line 50, in _run_chunk
2018-11-03 10:10:16 -     chunk.run()
2018-11-03 10:10:16 -   File "build/bdist.linux-x86_64/egg/athena/stages/assemble_meta_bins.py", line 82, in run
2018-11-03 10:10:16 -     self.do_local_assembly(ctg, asmdir)
2018-11-03 10:10:16 -   File "build/bdist.linux-x86_64/egg/athena/stages/assemble_meta_bins.py", line 147, in do_local_assembly
2018-11-03 10:10:16 -     local_asm_results = asm.assemble(local_asms, filt_ctgs=seed_ctgs)
2018-11-03 10:10:16 -   File "build/bdist.linux-x86_64/egg/athena/assembler_tools/barcode_assembler/local.py", line 83, in assemble
2018-11-03 10:10:16 -     contig_path = self._do_idba_assembly(local_asm)
2018-11-03 10:10:16 -   File "build/bdist.linux-x86_64/egg/athena/assembler_tools/barcode_assembler/local.py", line 173, in _do_idba_assembly
2018-11-03 10:10:16 -     raise Exception()
2018-11-03 10:10:16 - Exception
2018-11-03 10:10:16 -
2018-11-03 10:10:16 -
2018-11-03 10:10:16 - --starting logging AssembleMetaBinnedStep.bin.171 --
2018-11-03 10:10:16 - performing local assembly for 1 seeds
2018-11-03 10:10:16 - targeting 100x short-read subassembly coverage
2018-11-03 10:10:16 - using barcodes mapped within 10000bp from seed end-points for seed subassembly
2018-11-03 10:10:16 - assembling barcoded reads for seed NODE_2239_length_1159_cov_10.361413
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/athena/bin/athena-meta", line 11, in <module>
    load_entry_point('athena==1.1', 'console_scripts', 'athena-meta')()
  File "build/bdist.linux-x86_64/egg/main.py", line 104, in main
  File "build/bdist.linux-x86_64/egg/main.py", line 36, in run
  File "build/bdist.linux-x86_64/egg/athena/pipeline.py", line 33, in run_stage
  File "build/bdist.linux-x86_64/egg/athena/cluster.py", line 43, in map
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/athena/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
Exception
```

Why raise the exception instead of just skipping that subassembly? Currently, it appears that all bins have to result in contigs or else athena_meta will die. 

I'm also getting errors such as the following if I use >1 process for cluster_settings with multiprocessing:

```
2018-11-03 10:15:39 - performing local assemblies
2018-11-03 10:15:39 -   - skipping filtered contig NODE_66_length_45138_cov_17.962691
2018-11-03 10:15:39 - assembling with neighbor NODE_13841_length_362_cov_30.302932
2018-11-03 10:15:39 -   - 31 orig barcodes
2018-11-03 10:15:39 -   - 31 downsampled barcodes
2018-11-03 10:15:39 -   - 13.381294964x estimated local coverage
2018-11-03 10:15:39 -   - 2 min_support required
2018-11-03 10:15:39 - performing local assemblies
2018-11-03 10:15:39 -   - skipping filtered contig NODE_1669_length_1417_cov_63.982379
2018-11-03 10:15:39 - assembling with neighbor None
2018-11-03 10:15:39 -   - 1289 orig barcodes
2018-11-03 10:15:39 -   - 1289 downsampled barcodes
2018-11-03 10:15:39 -   - 38.04x estimated local coverage
2018-11-03 10:15:39 -   - 2 min_support required
2018-11-03 10:15:39 -   - 0 pass reciprocal filtering
2018-11-03 10:15:39 -   - 1 pass reciprocal filtering
2018-11-03 10:15:39 - root-ctg:NODE_368_length_6660_cov_9.626798;numreads:733;checks:2;trunc-checks:False;asms:0;trunc-asms:False
2018-11-03 10:15:39 -   - found 1 candidates
2018-11-03 10:15:39 - performing local assemblies
2018-11-03 10:15:39 - assembling with neighbor None
2018-11-03 10:15:39 -   - 375 orig barcodes
2018-11-03 10:15:39 -   - 375 downsampled barcodes
2018-11-03 10:15:39 -   - 16.509009009x estimated local coverage
2018-11-03 10:15:39 -   - 2 min_support required
2018-11-03 10:15:39 - root-ctg:NODE_5174_length_686_cov_28.564184;numreads:210;checks:4;trunc-checks:False;asms:1;trunc-asms:False
2018-11-03 10:15:39 -   - found 2 candidates
2018-11-03 10:15:39 - performing local assemblies
2018-11-03 10:15:39 - assembling with neighbor NODE_29_length_78920_cov_25.474697
2018-11-03 10:15:39 -   - 15 orig barcodes
2018-11-03 10:15:39 -   - 15 downsampled barcodes
2018-11-03 10:15:39 -   - 0.466409120889x estimated local coverage
2018-11-03 10:15:39 -   - 2 min_support required
2018-11-03 10:15:45 - ========== Exception ==========
2018-11-03 10:15:45 - Traceback (most recent call last):
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/pipeline.py", line 50, in _run_chunk
2018-11-03 10:15:45 -     chunk.run()
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/stages/assemble_meta_bins.py", line 82, in run
2018-11-03 10:15:45 -     self.do_local_assembly(ctg, asmdir)
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/stages/assemble_meta_bins.py", line 147, in do_local_assembly
2018-11-03 10:15:45 -     local_asm_results = asm.assemble(local_asms, filt_ctgs=seed_ctgs)
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/assembler_tools/barcode_assembler/local.py", line 83, in assemble
2018-11-03 10:15:45 -     contig_path = self._do_idba_assembly(local_asm)
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/assembler_tools/barcode_assembler/local.py", line 127, in _do_idba_assembly
2018-11-03 10:15:45 -     local_asm.ds_bcode_set,
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/assembler_tools/barcode_assembler/local.py", line 546, in get_bcode_reads
2018-11-03 10:15:45 -     for _, qname, lines in idx.get_reads(bcode):
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/mlib/fq_idx.py", line 110, in get_reads
2018-11-03 10:15:45 -     for e in util.fastq_iter(f):
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/mlib/util.py", line 138, in fastq_iter
2018-11-03 10:15:45 -     qname, info_map = _get_qname_info(lines[0])
2018-11-03 10:15:45 -   File "build/bdist.linux-x86_64/egg/athena/mlib/util.py", line 129, in _get_qname_info
2018-11-03 10:15:45 -     qname = elms[0]
2018-11-03 10:15:45 - IndexError: list index out of range
2018-11-03 10:15:45 -
2018-11-03 10:15:45 - list index out of range
Traceback (most recent call last):
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/athena/bin/athena-meta", line 11, in <module>
    load_entry_point('athena==1.1', 'console_scripts', 'athena-meta')()
  File "build/bdist.linux-x86_64/egg/main.py", line 104, in main
  File "build/bdist.linux-x86_64/egg/main.py", line 36, in run
  File "build/bdist.linux-x86_64/egg/athena/pipeline.py", line 33, in run_stage
  File "build/bdist.linux-x86_64/egg/athena/cluster.py", line 43, in map
  File "/ebio/abt3_projects/software/dev/miniconda3_dev/envs/athena/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IndexError: list index out of range
```

**Comment by nick-youngblut** [comment]
The errors where due to having the conda install of idba (1.1.3) in my PATH instead of idba-1.1.3a1. It would be great to include checks in athena-meta to catch is this happens. Also, I'm curious why idba_ud is used instead of spades or another assembler? Any chance that athena_meta will be upgraded to allow other assemblers and possibly modify parameters that those assemblers are using during the sub-assembly? As far as I can tell, currently no parameters (besides "cluster_settings") can be modified in athena_meta.

**Comment by bbsunchen** [comment]
same error here, with `virtualenv` install athena

**Comment by abishara** [comment]
Hi,

Yes, thanks for the input.  I agree additional checks to provide interpretable errors is desirable and I will provide these in an upcoming release.   Apologies for the delay.

With regards to idba_ud, there is actually some additional logic that I added to idba_ud, which is included in the referenced version you found.  In theory it is possible to use another short-read assembler like spades, but this additional logic would have to be implemented there for this to work.  Is there a reason you feel a different short-read assembler would work better?  During development, I found spades and idba_ud to perform comparably for subassembly and I picked idba_ud because the changes I needed to make were easier to make with it.

Best,
alex

**Comment by abishara** [comment]
Hi,

Error checking has now been added in commit 11dbe60f0d13.  Commit 4d6f201fdc2c added arguments --check_prereqs, to check that external dependencies are installed correctly, and --test, to run through a tiny test assembly to make sure the environment is properly setup.  Please let me know if you run into anymore issues with the inputs.
