### ISSUE TITLE
How does athena calling other programmes ? 

### ISSUE THREAD

**Issue by Zhong17** [abishara/athena_meta#18]
without installing  virtualenv, I have installed all the  required software and add in my environment path
(add the /path/to/software/bin to ~/.bashrc), and the athena were installed in ~/miniconda2/bin/athena-meta, when I run athena, the output showed that could not find bwa command:
$ athena-meta config.json 
============================== bin_reads ==============================
1 chunks to run. Starting...
2018-11-19 21:11:04 - --starting logging BinMetaReadsStep --
2018-11-19 21:11:04 - get seed contigs from input assembly
2018-11-19 21:11:04 - computing seed coverages (required pass thru *bam)
2018-11-19 21:11:04 -   3 total inputs seeds covering 809 bases
2018-11-19 21:11:04 -   1 input seed contigs >= 400bp and >= 10.0x coverage covering 400 bases
2018-11-19 21:11:04 - created 2 bins from seeds
2018-11-19 21:11:04 - -> finished running step; time elapsed: 0:00:00.030149
2018-11-19 21:11:04 - --stopping logging--
--> bin_reads completed.

============================== index_reads ==============================
1 chunks to run. Starting...
2018-11-19 21:11:04 - --starting logging IndexReadsStep_tianchen --
2018-11-19 21:11:04 - index fastq /home/tianchen/10x/barcoded.fastq
2018-11-19 21:11:04 - done
2018-11-19 21:11:04 - -> finished running step; time elapsed: 0:00:00.004956
2018-11-19 21:11:04 - --stopping logging--
--> index_reads completed.

============================== assemble_bins ==============================
2 chunks to run. Starting...
2018-11-19 21:11:05 - --starting logging AssembleMetaBinnedStep.bin.0 --
2018-11-19 21:11:05 - performing local assembly for 1 seeds
2018-11-19 21:11:05 - --starting logging AssembleMetaBinnedStep.bin.1 --
2018-11-19 21:11:05 - targeting 100x short-read subassembly coverage
2018-11-19 21:11:05 - using barcodes mapped within 10000bp from seed end-points for seed subassembly
2018-11-19 21:11:05 - performing local assembly for 0 seeds
2018-11-19 21:11:05 - targeting 100x short-read subassembly coverage
2018-11-19 21:11:05 - using barcodes mapped within 10000bp from seed end-points for seed subassembly
2018-11-19 21:11:05 - assembling barcoded reads for seed k99_25
2018-11-19 21:11:05 - merging all outputs
2018-11-19 21:11:05 - done
2018-11-19 21:11:05 - removing bin directory ./working/bin.1
2018-11-19 21:11:05 - -> finished running step; time elapsed: 0:00:00.000714
2018-11-19 21:11:05 - --stopping logging--
2018-11-19 21:11:05 - determing local assemblies
2018-11-19 21:11:05 - 0 initial link candidates to check
2018-11-19 21:11:05 -   - 0 pass reciprocal filtering
2018-11-19 21:11:05 - root-ctg:k99_25;numreads:136;checks:0;trunc-checks:False;asms:0;trunc-asms:False
2018-11-19 21:11:05 -   - found 1 candidates
2018-11-19 21:11:05 - performing local assemblies
2018-11-19 21:11:05 - assembling with neighbor None
2018-11-19 21:11:05 -   - 92 orig barcodes
2018-11-19 21:11:05 -   - 92 downsampled barcodes
2018-11-19 21:11:05 -   - 43.18x estimated local coverage
2018-11-19 21:11:05 -   - 2 min_support required
number of threads 2
reads 184
long reads 10
seed contigs 1
extra reads 0
read_length 150
kmer 20
kmers 4233 4243
merge bubble 0
contigs: 3 n50: 293 max: 293 mean: 125 total length: 375 n80: 62
aligned 8 reads
confirmed bases: 79 correct reads: 0 bases: 0
distance mean 86 sd 0
seed contigs 1 local contigs 6
kmer 40
kmers 931 926
merge bubble 0
contigs: 1 n50: 293 max: 293 mean: 293 total length: 293 n80: 293
aligned 8 reads
confirmed bases: 79 correct reads: 0 bases: 0
distance mean 86 sd 0
seed contigs 1 local contigs 2
kmer 60
kmers 354 354
merge bubble 0
contigs: 1 n50: 293 max: 293 mean: 293 total length: 293 n80: 293
aligned 8 reads
confirmed bases: 79 correct reads: 0 bases: 0
distance mean 86 sd 0
seed contigs 1 local contigs 2
kmer 80
kmers 330 328
merge bubble 0
contigs: 1 n50: 293 max: 293 mean: 293 total length: 293 n80: 293
aligned 8 reads
confirmed bases: 79 correct reads: 0 bases: 0
distance mean 86 sd 0
seed contigs 1 local contigs 2
kmer 100
kmers 194 193
merge bubble 0
contigs: 1 n50: 0 max: 0 mean: 0 total length: 0 n80: 0
aligning seed contigs
  - 0 aligned
hit 0 connected components
  - retained 0 of 0 contigs
reads 184
aligned 0 reads
distance mean -nan sd -nan
invalid insert distance
:::: -11
2018-11-19 21:11:05 - something funky happened while running idba_ud (got error code -11) but there's not much we can do so continuing
2018-11-19 21:11:05 - failed to produce correctly formatted contigs in ./working/bin.0/asm/k99_25/local-asm.0/contig.fa
2018-11-19 21:11:05 -   - finished 1
2018-11-19 21:11:05 - merge long output contigs from local assemblies
2018-11-19 21:11:05 - contig path for local asm k99_25_None.0 not generated
2018-11-19 21:11:05 -   - 0 contigs covering 0 bases
2018-11-19 21:11:05 - merging all outputs
2018-11-19 21:11:05 - done
2018-11-19 21:11:05 - removing bin directory ./working/bin.0
2018-11-19 21:11:05 - -> finished running step; time elapsed: 0:00:00.428354
2018-11-19 21:11:05 - --stopping logging--
--> assemble_bins completed.

============================== assemble_olc ==============================
1 chunks to run. Starting...
2018-11-19 21:11:05 - --starting logging AssembleOLCStep --
2018-11-19 21:11:05 - jointly overlap-assemble
2018-11-19 21:11:05 - merge input contigs
cmd bwa mem -t 4 /home/tianchen/10x/final.contigs.fa ./results/olc/pre-flye-input-contigs.fa | samtools view -bS - | samtools sort -o ./results/olc/align-inputs.bam - 
**_/bin/sh: bwa: command not found_**
cmd samtools index ./results/olc/align-inputs.bam
2018-11-19 21:11:05 - filter short subassembled contigs and merge with seeds
2018-11-19 21:11:05 - ========== Exception ==========
2018-11-19 21:11:05 - Traceback (most recent call last):
2018-11-19 21:11:05 -   File "/home/tianchen/miniconda2/lib/python2.7/site-packages/athena/pipeline.py", line 50, in _run_chunk
2018-11-19 21:11:05 -     chunk.run()
2018-11-19 21:11:05 -   File "/home/tianchen/miniconda2/lib/python2.7/site-packages/athena/stages/assemble_olc.py", line 96, in run
2018-11-19 21:11:05 -     premergedfiltfa_path,
2018-11-19 21:11:05 -   File "/home/tianchen/miniconda2/lib/python2.7/site-packages/athena/stages/assemble_olc.py", line 160, in filter_inputs
2018-11-19 21:11:05 -     ctg_size_map = util.get_fasta_sizes(mergedfa_path)
2018-11-19 21:11:05 -   File "/home/tianchen/miniconda2/lib/python2.7/site-packages/athena/mlib/util.py", line 151, in get_fasta_sizes
2018-11-19 21:11:05 -     fasta = pysam.FastaFile(fa_path)
2018-11-19 21:11:05 -   File "pysam/libcfaidx.pyx", line 123, in pysam.libcfaidx.FastaFile.__cinit__
2018-11-19 21:11:05 -   File "pysam/libcfaidx.pyx", line 183, in pysam.libcfaidx.FastaFile._open
2018-11-19 21:11:05 - IOError: error when opening file `./results/olc/pre-flye-input-contigs.fa`
2018-11-19 21:11:05 - 
2018-11-19 21:11:05 - error when opening file `./results/olc/pre-flye-input-contigs.fa`
Traceback (most recent call last):
  File "/home/tianchen/miniconda2/bin/athena-meta", line 11, in <module>
    sys.exit(main())
  File "/home/tianchen/miniconda2/lib/python2.7/site-packages/main.py", line 104, in main
    run(options)
  File "/home/tianchen/miniconda2/lib/python2.7/site-packages/main.py", line 36, in run
    runner.run_stage(stage, stage_name)
  File "/home/tianchen/miniconda2/lib/python2.7/site-packages/athena/pipeline.py", line 33, in run_stage
    cluster.map(_run_chunk, to_run)
  File "/home/tianchen/miniconda2/lib/python2.7/site-packages/athena/cluster.py", line 43, in map
    return pool.map_async(fn, args).get(9999999)
  File "/home/tianchen/miniconda2/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
IOError: error when opening file `./results/olc/pre-flye-input-contigs.fa`
 

and also, the error showed that fail to open the ./results/olc/pre-flye-input-contigs.fa.
I think I need help,thanks!

**Comment by abishara** [comment]
If it's easier for setup, please see #13.  Athena can now be installed using conda.
