### ISSUE TITLE
athena_meta install error

### ISSUE THREAD

**Issue by tina-666** [abishara/athena_meta#19]
when I used the $pip install -r requirements.txt, the error is 

pip install -r requirements.txt
Collecting bx-python==0.7.3 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/55/db/fa76af59a03c88ad80494fc0df2948740bbd58cd3b3ed5c31319624687cc/bx-python-0.7.3.tar.gz
Collecting ipython-cluster-helper==0.5.2 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/97/df/8a9b0ef7657344bdad15ba9bc187c8d5182f27d5afda51c493a961d0f9a1/ipython-cluster-helper-0.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-cq2sb9t7/ipython-cluster-helper/setup.py", line 3, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-cq2sb9t7/ipython-cluster-helper/

how can I solve the problem?

**Comment by abishara** [comment]
Hi,

Can you do pip --version?  I think there are some versions after pip version 9.0.2, in which the ipython-cluster-help setup fails.  However, I just tried pip 18.1 and this seems to work again.

Can you either try updating to this later version of pip or downgrading to an earlier one with:

% pip install pip==9.0.2

Let me know how that goes.  

alex

**Comment by abishara** [comment]
If it's easier for setup, please see #13. Athena can now be installed using conda.
