### ISSUE TITLE
Flye error

### ISSUE THREAD

**Issue by juansearch** [abishara/athena_meta#21]
Dear Athena,
I am running Athena-meta on linked-read data through a docker. I started the run, everything seems to be running OK but then it crashes with the following error:

2019-02-09 12:34:10 - Command 'flye --subassemblies ./results/olc/flye-input-contigs.fa --out-dir ./results/olc/flye-asm-1 --genome-size 41031 --threads 64 --min-overlap 1000' returned non-zero exit status 1
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 389, in _handle_results
    task = get()
TypeError: ('__init__() takes at least 3 arguments (1 given)', <class 'subprocess.CalledProcessError'>, ())

Please help,
Juan

**Comment by abishara** [comment]
Hi Juan,

Are you using the docker image `abishara/athena-meta-flye-docker`?  

It's a little hard to tell from the output copied what exactly is going on.  Relative to your `config.json` file can you remove the olc subdirectory with `rm -rf ./results/olc`, rerun with a single thread (`athena-meta --threads 1`), and then upload the full log output if it continues to fail?

Thanks!
alex

**Comment by johnne** [comment]
Hi @abishara,
I ran into this issue as well. After upgrading flye to version 2.4.2 (which downgrades athena_meta to v. 1.2) `athena-meta` completes without an error. What was the reason for switching Flye to version 2.3.1?

Cheers,
John

**Comment by abishara** [comment]
Hi @johnne 

I switched to version 2.3.1 once I noticed that `athena-meta --test` failed for flye 2.4.1.  To be honest,  I'm not quite sure why I didn't stick to 2.4.2 looking back at this, might be oversight.  I just ran with flye 2.4.2 and see that `athena-meta --test` passes.

Can you clarify what error you are observing though?  Installing `athena_meta` versions `1.2` or `1.3` through conda both work for me at the moment.

Thanks,
alex
