### ISSUE TITLE
Error: Cannot allocate memory

### ISSUE THREAD

**Issue by nkalsi22** [abishara/athena_meta#27]
Hi, 
I'm trying to run Athena on a dataset with 16 CPU cores and "--threads 16". I've previously run Athena with the same specifications successfully. 
On checking the logs directory, it's the "SubassembleReadsStep.bin.1" that's giving the memory error. 

$ cat SubassembleReadsStep.bin.1
2019-07-18 13:20:54 - DEBUG - --starting logging SubassembleReadsStep.bin.1 --
2019-07-18 13:20:54 - DEBUG - performing local assembly for 26 seeds
2019-07-18 13:20:54 - DEBUG - targeting 100x short-read subassembly coverage
2019-07-18 13:20:54 - DEBUG - using barcodes mapped within 10000bp from seed end-points for seed subassembly
2019-07-18 13:20:54 - DEBUG - assembling barcoded reads for seed NODE_3594604_length_400_cov_20.831884
2019-07-18 13:22:03 - DEBUG - determing local assemblies
2019-07-18 13:22:14 - DEBUG - 2 initial link candidates to check
2019-07-18 13:22:14 - DEBUG -   - 2 pass reciprocal filtering
2019-07-18 13:22:19 - DEBUG - root-ctg:NODE_3594604_length_400_cov_20.831884;numreads:52;checks:2;trunc-checks:False;asms:2;trunc-asms:False
2019-07-18 13:22:19 - DEBUG -   - found 3 candidates
2019-07-18 13:22:24 - DEBUG - performing local assemblies
2019-07-18 13:22:24 - DEBUG - assembling with neighbor NODE_266230_length_1759_cov_19.257629
2019-07-18 13:22:24 - DEBUG -   - 19 orig barcodes
2019-07-18 13:22:24 - DEBUG -   - 19 downsampled barcodes
2019-07-18 13:22:24 - DEBUG -   - 8.18351187704x estimated local coverage
2019-07-18 13:22:24 - DEBUG -   - 2 min_support required
2019-07-18 13:22:52 - ERROR - ========== Exception ==========
2019-07-18 13:22:52 - ERROR - Traceback (most recent call last):
2019-07-18 13:22:52 - ERROR -   File "/cm/shared/apps/bio/athena_meta/1.3/lib/python2.7/site-packages/athena/pipeline.py", line 51, in _run_chunk
2019-07-18 13:22:52 - ERROR -     chunk.run()
2019-07-18 13:22:52 - ERROR -   File "/cm/shared/apps/bio/athena_meta/1.3/lib/python2.7/site-packages/athena/stages/subassemble_reads.py", line 80, in run
2019-07-18 13:22:52 - ERROR -     self.do_local_assembly(ctg, asmdir)
2019-07-18 13:22:52 - ERROR -   File "/cm/shared/apps/bio/athena_meta/1.3/lib/python2.7/site-packages/athena/stages/subassemble_reads.py", line 147, in do_local_assembly
2019-07-18 13:22:52 - ERROR -     local_asm_results = asm.assemble(local_asms, filt_ctgs=seed_ctgs)
2019-07-18 13:22:52 - ERROR -   File "/cm/shared/apps/bio/athena_meta/1.3/lib/python2.7/site-packages/athena/subassembly/barcode_assembler.py", line 83, in assemble
2019-07-18 13:22:52 - ERROR -     contig_path = self._do_idba_assembly(local_asm)
2019-07-18 13:22:52 - ERROR -   File "/cm/shared/apps/bio/athena_meta/1.3/lib/python2.7/site-packages/athena/subassembly/barcode_assembler.py", line 160, in _do_idba_assembly
2019-07-18 13:22:52 - ERROR -     stderr=subprocess.PIPE,
2019-07-18 13:22:52 - ERROR -   File "/cm/shared/apps/devel/python/Python-2.7.16/lib/python2.7/subprocess.py", line 394, in __init__
2019-07-18 13:22:52 - ERROR -     errread, errwrite)
2019-07-18 13:22:52 - ERROR -   File "/cm/shared/apps/devel/python/Python-2.7.16/lib/python2.7/subprocess.py", line 938, in _execute_child
2019-07-18 13:22:52 - ERROR -     self.pid = os.fork()
2019-07-18 13:22:52 - ERROR - OSError: [Errno 12] Cannot allocate memory
2019-07-18 13:22:52 - ERROR - 
2019-07-18 13:22:52 - ERROR - [Errno 12] Cannot allocate memory

**Comment by abishara** [comment]
Hi Namrata,

Sorry for the delayed response.  From the root working directory, could you please print the output of:

```
% ls -lth working/bin.1/asm/NODE_3594604_length_400_cov_20.831884/fqs
```

so I can get a sense of the file size.  I think one of these is somehow too large.  Better yet, you could actually upload the raw files that are in there and share a link with me so that I can take a look.

Thanks!
alex

**Comment by nkalsi22** [comment]
Hi Alex,



(base) [namrata@ln-0001 athena_new_16]$ ls -lth working/bin.1/asm/NODE_3594604_length_400_cov_20.831884/fqs

total 896K

-rw-r--r-- 1 namrata research  18K Jul 18 13:22 lr-hints.0.fa

-rw-r--r-- 1 namrata research 1.8K Jul 18 13:22 seeds.0.fa

-rw-r--r-- 1 namrata research 685K Jul 18 13:22 reads.0.ds.fa

The files aren’t too big.

Namrata

**Comment by abishara** [comment]
Hmm, that is a bit odd/unexpected.  Can you upload them and share a link?  It'll be hard for me to determine the source of issue otherwise.

Thanks!
alex

**Comment by nkalsi22** [comment]
Hi,
I sent the files in the previous email as attachments, but here’s the link.

https://www.dropbox.com/sh/2c4w13pw3694qcl/AAALK_aEsDMJxg0WPIr0E6DJa?dl=0

Namrata

**Comment by abishara** [comment]
Hmm, something isn't quite making sense.  I ran it on those files and it terminated without an issue.   A few thoughts:

1) Are you running it with the sufficient memory allocation from your resource manager? (assuming you are using one)

2) Are these reads uploaded from the same run in which you originally obtained the error?  Can you copy the output from your working directory of `ls -lhS working/bin.*/asm/*/fqs/*fa | head -20` just to make sure I didn't misinterpret which subassembly is causing it fail?

3) If we don't get insight from that, I think the only way for me to try to understand the problem is for me to run it on the inputs specified in your `config.json` directly.  

Thanks,
alex

**Comment by abishara** [comment]
@nkalsi22 Did this get resolved?  Still happy to take a look if you are having issues.

Best,
alex
