### ISSUE TITLE
Missing scaffolds.fasta 

### ISSUE THREAD

**Issue by davidvilanova** [abishara/athena_meta#29]
Hello,
I get a missing scaffolds.fasta as follows:

My data was assembled with megahit (rather than metaspades).

```
[2019-08-13 18:45:16] INFO: Assembly statistics:

        Total length:   31516514
        Fragments:      364
        Fragments N50:  425866
        Largest frg:    1399380
        Scaffolds:      1
        Mean coverage:  6

[2019-08-13 18:45:16] INFO: Final assembly: /home/david/files/athena/10X-GivMock/resul
ts/olc/flye-asm-1/assembly.fasta
2019-08-13 18:45:16 - ERROR - ========== Exception ==========
2019-08-13 18:45:16 - ERROR - Traceback (most recent call last):
2019-08-13 18:45:16 - ERROR -   File "/home/david/work/miniconda3/envs/python2.7/lib/python2.7/site-packages/athena/pipeline.py", line 51, in _run_chun
k
2019-08-13 18:45:16 - ERROR -     chunk.run()
2019-08-13 18:45:16 - ERROR -   File "/home/david/work/miniconda3/envs/python2.7/lib/python2.7/site-packages/athena/stages/assemble_olc.py", line 162,
in run
2019-08-13 18:45:16 - ERROR -     shutil.copy(flye_contigs_path, final_fa_path)
2019-08-13 18:45:16 - ERROR -   File "/home/david/work/miniconda3/envs/python2.7/lib/python2.7/shutil.py", line 133, in copy
2019-08-13 18:45:16 - ERROR -     copyfile(src, dst)
2019-08-13 18:45:16 - ERROR -   File "/home/david/work/miniconda3/envs/python2.7/lib/python2.7/shutil.py", line 96, in copyfile
2019-08-13 18:45:16 - ERROR -     with open(src, 'rb') as fsrc:
2019-08-13 18:45:16 - ERROR - IOError: [Errno 2] No such file or directory: 'files/athena/10X-testMock/results/olc/flye-asm-1/scaffolds.fasta'
2019-08-13 18:45:16 - ERROR -
2019-08-13 18:45:16 - ERROR - [Errno 2] No such file or directory: 'files/athena/10X-testMock/results/olc/flye-asm-1/scaffolds.fasta'

```

**Comment by abishara** [comment]
Hi,

Hmm, it shouldn't matter if you are using megahit instead for the inputs.  From your root directory can you copy the output of the following:

```
% ls -lh results/olc/flye-asm-1
% flye --version
```

However, just from looking at the log file line you copied, it appears `flye` put the results in `assembly.fasta`.  This leads me to believe you might be using a newer or older version of `flye` than the one that is expected.  The current released version of Athena uses `flye` 2.3.1-release

Thanks,
alex

**Comment by davidvilanova** [comment]
Oh yes I´m using flye 2.5-release (was already using it for other assemblies), that might be the problem. No scaffolds.fasta in results/olc/flye-asm-1

**Comment by davidvilanova** [comment]
By the way i´have also tested with metaspades and flye 2.5-release and it go all the way through without any error. Metaspades produces the scaffolds.fasta

**Comment by davidvilanova** [comment]
I have also tested with metaspades and same probelm. I will downgrade flye and check.
```
ls -1 files/athena/10X-testMock/results/olc/flye-asm-1/
00-assembly
20-repeat
30-contigger
40-polishing
assembly.fasta
assembly_graph.gfa
assembly_graph.gv
assembly_info.txt
flye.log
params.json

```

**Comment by abishara** [comment]
Yes, I don't think it's related to metaspades vs megahit.  I'd be surprised if it ever worked with flye 2.5-release given the outputs do not seem to match what is expected.  Let me know if downgrading flye takes care of it.  You should only need to `rm -rf results/olc` and can rerun from the same working directory upon downgrading.

**Comment by davidvilanova** [comment]
Downgrade to flye 2.3.1 dit the trick.
Would be great to use later versions of flye  as many improvements have been added. Thanks.

**Comment by abishara** [comment]
Okay, good to hear that fixed it for now.

I agree, let me look into doing this and get back to you.

Thanks!
alex
