### ISSUE TITLE
Error during assemble_olc : AssertionError: merge FASTA not valid 

### ISSUE THREAD

**Issue by senaj** [abishara/athena_meta#31]
I received the following error when running athena. Please, can you help me determine what caused the error and provide suggestions to fix the problem?

============================== assemble_olc ==============================
1 chunks to run. Starting...
2019-12-27 21:55:37 - ERROR - ========== Exception ==========
2019-12-27 21:55:37 - ERROR - Traceback (most recent call last):
2019-12-27 21:55:37 - ERROR -   File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/pipeline.py", line 5
1, in _run_chunk
2019-12-27 21:55:37 - ERROR -     chunk.run()
2019-12-27 21:55:37 - ERROR -   File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/stages/assemble_olc.
py", line 135, in run
2019-12-27 21:55:37 - ERROR -     assert is_valid_fasta(mergedfiltfa_path), "merge FASTA not valid"
2019-12-27 21:55:37 - ERROR - AssertionError: merge FASTA not valid
2019-12-27 21:55:37 - ERROR -
2019-12-27 21:55:37 - ERROR - merge FASTA not valid
Traceback (most recent call last):
  File "/home/s953272/ATHENA_META_ENV/bin/athena-meta", line 11, in <module>
    sys.exit(main())
  File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/main.py", line 211, in main
    run(options)
  File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/main.py", line 42, in run
    runner.run_stage(stage, stage_name)
  File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/pipeline.py", line 33, in run_stage
    cluster.map(_run_chunk, to_run)
  File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/cluster.py", line 43, in map
    return pool.map_async(fn, args).get(9999999)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
    raise self._value
AssertionError: merge FASTA not valid
Command exited with non-zero status 1

**Comment by juyanmei** [comment]
> I received the following error when running athena. Please, can you help me determine what caused the error and provide suggestions to fix the problem?
> 
> ============================== assemble_olc ==============================
> 1 chunks to run. Starting...
> 2019-12-27 21:55:37 - ERROR - ========== Exception ==========
> 2019-12-27 21:55:37 - ERROR - Traceback (most recent call last):
> 2019-12-27 21:55:37 - ERROR - File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/pipeline.py", line 5
> 1, in _run_chunk
> 2019-12-27 21:55:37 - ERROR - chunk.run()
> 2019-12-27 21:55:37 - ERROR - File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/stages/assemble_olc.
> py", line 135, in run
> 2019-12-27 21:55:37 - ERROR - assert is_valid_fasta(mergedfiltfa_path), "merge FASTA not valid"
> 2019-12-27 21:55:37 - ERROR - AssertionError: merge FASTA not valid
> 2019-12-27 21:55:37 - ERROR -
> 2019-12-27 21:55:37 - ERROR - merge FASTA not valid
> Traceback (most recent call last):
> File "/home/s953272/ATHENA_META_ENV/bin/athena-meta", line 11, in
> sys.exit(main())
> File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/main.py", line 211, in main
> run(options)
> File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/main.py", line 42, in run
> runner.run_stage(stage, stage_name)
> File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/pipeline.py", line 33, in run_stage
> cluster.map(_run_chunk, to_run)
> File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/cluster.py", line 43, in map
> return pool.map_async(fn, args).get(9999999)
> File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
> raise self._value
> AssertionError: merge FASTA not valid
> Command exited with non-zero status 1

I had the same error, did you fix it?

**Comment by senaj** [comment]
> > I received the following error when running athena. Please, can you help me determine what caused the error and provide suggestions to fix the problem?
> > ============================== assemble_olc ==============================
> > 1 chunks to run. Starting...
> > 2019-12-27 21:55:37 - ERROR - ========== Exception ==========
> > 2019-12-27 21:55:37 - ERROR - Traceback (most recent call last):
> > 2019-12-27 21:55:37 - ERROR - File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/pipeline.py", line 5
> > 1, in _run_chunk
> > 2019-12-27 21:55:37 - ERROR - chunk.run()
> > 2019-12-27 21:55:37 - ERROR - File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/stages/assemble_olc.
> > py", line 135, in run
> > 2019-12-27 21:55:37 - ERROR - assert is_valid_fasta(mergedfiltfa_path), "merge FASTA not valid"
> > 2019-12-27 21:55:37 - ERROR - AssertionError: merge FASTA not valid
> > 2019-12-27 21:55:37 - ERROR -
> > 2019-12-27 21:55:37 - ERROR - merge FASTA not valid
> > Traceback (most recent call last):
> > File "/home/s953272/ATHENA_META_ENV/bin/athena-meta", line 11, in
> > sys.exit(main())
> > File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/main.py", line 211, in main
> > run(options)
> > File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/main.py", line 42, in run
> > runner.run_stage(stage, stage_name)
> > File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/pipeline.py", line 33, in run_stage
> > cluster.map(_run_chunk, to_run)
> > File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/cluster.py", line 43, in map
> > return pool.map_async(fn, args).get(9999999)
> > File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
> > raise self._value
> > AssertionError: merge FASTA not valid
> > Command exited with non-zero status 1
> 
> I had the same error, did you fix it?

Hi, juyanmei 

No, I did not solve this problem. I contacted the research team that developed the software and they were very responsive except for the individual who wrote the program. They still have not fixed this issue.

**Comment by juyanmei** [comment]
> > > I received the following error when running athena. Please, can you help me determine what caused the error and provide suggestions to fix the problem?
> > > ============================== assemble_olc ==============================
> > > 1 chunks to run. Starting...
> > > 2019-12-27 21:55:37 - ERROR - ========== Exception ==========
> > > 2019-12-27 21:55:37 - ERROR - Traceback (most recent call last):
> > > 2019-12-27 21:55:37 - ERROR - File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/pipeline.py", line 5
> > > 1, in _run_chunk
> > > 2019-12-27 21:55:37 - ERROR - chunk.run()
> > > 2019-12-27 21:55:37 - ERROR - File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/stages/assemble_olc.
> > > py", line 135, in run
> > > 2019-12-27 21:55:37 - ERROR - assert is_valid_fasta(mergedfiltfa_path), "merge FASTA not valid"
> > > 2019-12-27 21:55:37 - ERROR - AssertionError: merge FASTA not valid
> > > 2019-12-27 21:55:37 - ERROR -
> > > 2019-12-27 21:55:37 - ERROR - merge FASTA not valid
> > > Traceback (most recent call last):
> > > File "/home/s953272/ATHENA_META_ENV/bin/athena-meta", line 11, in
> > > sys.exit(main())
> > > File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/main.py", line 211, in main
> > > run(options)
> > > File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/main.py", line 42, in run
> > > runner.run_stage(stage, stage_name)
> > > File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/pipeline.py", line 33, in run_stage
> > > cluster.map(_run_chunk, to_run)
> > > File "/home/s953272/ATHENA_META_ENV/lib/python2.7/site-packages/athena/cluster.py", line 43, in map
> > > return pool.map_async(fn, args).get(9999999)
> > > File "/usr/lib64/python2.7/multiprocessing/pool.py", line 554, in get
> > > raise self._value
> > > AssertionError: merge FASTA not valid
> > > Command exited with non-zero status 1
> > 
> > 
> > I had the same error, did you fix it?
> 
> Hi, juyanmei
> 
> No, I did not solve this problem. I contacted the research team that developed the software and they were very responsive except for the individual who wrote the program. They still have not fixed this issue.

Hi, 
senaj, I ran successfully by using contigs.fasta rather than scaffolds.fasta.
