### ISSUE TITLE
Hi, I want to know what 'integer sample identifier' means in the FASTQ formatting tips.

### ISSUE THREAD

**Issue by dmsalsgh97** [abishara/athena_meta#34]
Hi, I want to know what 'integer sample identifier' means in the following:

![image](https://user-images.githubusercontent.com/42495757/75142043-91401280-5735-11ea-810d-e9c43617893b.png)

Just adding '-1'for all fastq file is needed?
Thx.

**Comment by Chris-lad** [comment]
Hello @dmsalsgh97 !!! Tell me please : were you able to run properly athena_meta ?

**Comment by dmsalsgh97** [comment]
> Hello @dmsalsgh97 !!! Tell me please : were you able to run properly athena_meta ?

Yes. Is there any problem?
It worked well

**Comment by Chris-lad** [comment]
Yes !! There is a problem.
Its not working well for me

Here is my error

============================== check_reads ==============================
1 chunks to run. Starting...
2021-01-23 19:03:57 - INFO - index fastq /mnt/c/Users/blado/Desktop/workTeam1/firststep/reads.fq
2021-01-23 19:03:57 - INFO - get seed contigs from input assembly
2021-01-23 19:03:57 - INFO - computing seed coverages (required pass thru *bam)
2021-01-23 19:03:58 - INFO -   52 total inputs seeds covering 67751 bases
2021-01-23 19:03:58 - INFO -   3 input seed contigs >= 400bp and >= 10.0x coverage covering 39301 bases
2021-01-23 19:03:58 - INFO - created 4 bins from seeds
2021-01-23 19:03:58 - INFO - done
--> check_reads completed.

============================== subassemble_reads ==============================
4 chunks to run. Starting...
2021-01-23 19:03:58 - INFO - finished subassembly bin.3
2021-01-23 19:03:58 - INFO - finished subassembly bin.1
2021-01-23 19:04:19 - INFO - finished subassembly bin.2
2021-01-23 19:04:23 - INFO - finished subassembly bin.0
--> subassemble_reads completed.

============================== assemble_olc ==============================
1 chunks to run. Starting...
2021-01-23 19:04:24 - INFO - merge input contigs
2021-01-23 19:04:24 - INFO - filter short subassembled contigs and merge with seeds
2021-01-23 19:04:24 - INFO -   - 5 filtered of 8 original contigs remaining
2021-01-23 19:04:24 - INFO - launching Flye OLC assembly
2021-01-23 19:04:24 - INFO -   - cmd:flye --subassemblies ./results/olc/flye-input-contigs.fa --out-dir ./results/olc/flye-asm-1 --genome-size 39301 --threads 4 --min-overlap 1000
[2021-01-23 19:04:26] INFO: Running Flye 2.3.1-release
[2021-01-23 19:04:26] INFO: Assembling reads
[2021-01-23 19:04:26] INFO: Reading sequences
[2021-01-23 19:04:26] INFO: Generating solid k-mer index
[2021-01-23 19:04:59] INFO: Counting kmers (1/2):
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-23 19:04:59] INFO: Counting kmers (2/2):
0% % 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-23 19:04:59] INFO: Filling index table
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-23 19:05:00] INFO: Extending reads
0% 10% 20% 4030% % 6050% 80% 9070% % 10% % % 0% %
[2021-01-23 19:05:00] INFO: Added 6 singleton reads
[2021-01-23 19:05:00] INFO: Assembled 8 draft contigs
[2021-01-23 19:05:00] INFO: Generating contig sequences
10% 20% 40% 50% 70% 80% 100%
[2021-01-23 19:05:00] INFO: Performing repeat analysis
[2021-01-23 19:05:00] INFO: Reading sequences
[2021-01-23 19:05:00] INFO: Building repeat graph
0% 10% 20% 30% 40% 50% % 60% 70% 80% 90% 100%
[2021-01-23 19:05:34] INFO: Aligning reads to the graph
0% 10% 20% 30% 40% 50% 60% 70% 80% 90% 100%
[2021-01-23 19:06:08] ERROR: Segmentation fault! Backtrace:
[2021-01-23 19:06:08] ERROR:    flye-repeat() [0x41a0ae]
[2021-01-23 19:06:08] ERROR:    /lib/x86_64-linux-gnu/libc.so.6(+0x46210) [0x7f9a89866210]
[2021-01-23 19:06:08] ERROR:    flye-repeat() [0x42665d]
[2021-01-23 19:06:08] ERROR:    flye-repeat() [0x4242c9]
[2021-01-23 19:06:08] ERROR:    flye-repeat() [0x404f8c]
[2021-01-23 19:06:08] ERROR:    /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f9a898470b3]
[2021-01-23 19:06:08] ERROR:    flye-repeat() [0x405f41]
[2021-01-23 19:06:08] ERROR: Command '['flye-repeat', '-k', '15', '-l', '/mnt/c/Users/blado/Desktop/workTeam1/firststep/results/olc/flye-asm-1/flye.log', '-t', '4', '-v', '1000', '/mnt/c/Users/blado/Desktop/workTeam1/firststep/results/olc/flye-asm-1/0-assembly/draft_assembly.fasta', './results/olc/flye-input-contigs.fa', '/mnt/c/Users/blado/Desktop/workTeam1/firststep/results/olc/flye-asm-1/2-repeat', '/home/chris/miniconda3/envs/myenv2/lib/python2.7/site-packages/flye/resource/asm_corrected_reads.cfg']' returned non-zero exit status 1
2021-01-23 19:06:08 - ERROR - ========== Exception ==========
2021-01-23 19:06:08 - ERROR - Traceback (most recent call last):
2021-01-23 19:06:08 - ERROR -   File "/home/chris/miniconda3/envs/myenv2/lib/python2.7/site-packages/athena/pipeline.py", line 51, in _run_chunk
2021-01-23 19:06:08 - ERROR -     chunk.run()
2021-01-23 19:06:08 - ERROR -   File "/home/chris/miniconda3/envs/myenv2/lib/python2.7/site-packages/athena/stages/assemble_olc.py", line 158, in run
2021-01-23 19:06:08 - ERROR -     subprocess.check_call(cmd, shell=True)
2021-01-23 19:06:08 - ERROR -   File "/home/chris/miniconda3/envs/myenv2/lib/python2.7/subprocess.py", line 190, in check_call
2021-01-23 19:06:08 - ERROR -     raise CalledProcessError(retcode, cmd)
2021-01-23 19:06:08 - ERROR - CalledProcessError: Command 'flye --subassemblies ./results/olc/flye-input-contigs.fa --out-dir ./results/olc/flye-asm-1 --genome-size 39301 --threads 4 --min-overlap 1000' returned non-zero exit status 1
2021-01-23 19:06:08 - ERROR -
2021-01-23 19:06:08 - ERROR - Command 'flye --subassemblies ./results/olc/flye-input-contigs.fa --out-dir ./results/olc/flye-asm-1 --genome-size 39301 --threads 4 --min-overlap 1000' returned non-zero exit status 1
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/home/chris/miniconda3/envs/myenv2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/chris/miniconda3/envs/myenv2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/chris/miniconda3/envs/myenv2/lib/python2.7/multiprocessing/pool.py", line 392, in _handle_results
    task = get()
TypeError: __init__() takes at least 3 arguments (1 given)

**Comment by Chris-lad** [comment]
I solved this issue by downdrading athena.
I've encountered many errors while trying to assemble my metagenome with athena_meta 1.3 which come with flye 2.3.1.
I solved my issue by downgrading athena_meta from 1.3 to 1.2.

Athena 1.2 comes with flye 2.4.2 which actually works perfectly without throwing error!!


Hope this will help someone
